const logoItems = [
  { id: 1, name: "Билайн", image: "/images/Ray-Ban.png" },
  { id: 2, name: "IDS Borjomi", image: "/images/Ray-Ban.png" },
  { id: 3, name: "Abbott", image: "/images/Ray-Ban.png" },
  { id: 4, name: "Ак Барс Банк", image: "/images/Ray-Ban.png" },
  { id: 5, name: "Альфа Банк", image: "/images/Ray-Ban.png" },
  { id: 6, name: "AQUIND", image: "/images/Ray-Ban.png" },
  { id: 7, name: "Askona", image: "/images/Ray-Ban.png" },
  { id: 8, name: "Автодор", image: "/images/Ray-Ban.png" },
  { id: 9, name: "BELKA CAR", image: "/images/Ray-Ban.png" },
  { id: 10, name: "Familia", image: "/images/Ray-Ban.png" },
  { id: 11, name: "GRASS", image: "/images/Ray-Ban.png" },
  { id: 12, name: "Henkel", image: "/images/Ray-Ban.png" },
  { id: 13, name: "hh", image: "/images/Ray-Ban.png" },
  { id: 14, name: "ИВИ", image: "/images/Ray-Ban.png" },
  { id: 15, name: "KIA", image: "/images/Ray-Ban.png" },
  { id: 16, name: "KNAUF", image: "/images/Ray-Ban.png" },
  { id: 17, name: "Merck", image: "/images/Ray-Ban.png" },
  { id: 18, name: "VIPPLAY", image: "/images/Ray-Ban.png" },
  { id: 19, name: "Ozon Travel", image: "/images/Ray-Ban.png" },
  { id: 20, name: "QIWI", image: "/images/Ray-Ban.png" },
  { id: 21, name: "Работа.ру", image: "/images/Ray-Ban.png" },
  { id: 22, name: "Ренессанс Страхование", image: "/images/Ray-Ban.png" },
  { id: 23, name: "РОСКОНГРЕСС", image: "/images/Ray-Ban.png" },
  { id: 24, name: "Совкомбанк", image: "/images/Ray-Ban.png" },
  { id: 25, name: "SKODA", image: "/images/Ray-Ban.png" },
  { id: 26, name: "Decathlon", image: "/images/Ray-Ban.png" },
  { id: 27, name: "DNS", image: "/images/Ray-Ban.png" },
  { id: 28, name: "Ozon", image: "/images/Ray-Ban.png" },
  { id: 29, name: "Мегафон", image: "/images/Ray-Ban.png" },
  { id: 30, name: "МТС", image: "/images/Ray-Ban.png" },
  { id: 31, name: "М.Видео", image: "/images/Ray-Ban.png" },
  { id: 32, name: "Кошелёк", image: "/images/Ray-Ban.png" },
  { id: 33, name: "X5 Group", image: "/images/Ray-Ban.png" },
];

export default logoItems;
