const logoItems = [
  { id: 1, name: "JAM", image: "/images/clients-logo/JAM.png" },
  { id: 2, name: "IIHF", image: "/images/clients-logo/IIHF_logo.png" },
  { id: 3, name: "Duma", image: "/images/clients-logo/Moscow_City_Duma_Logo.png" },
  { id: 4, name: "Gazprom", image: "/images/clients-logo/Gazprom_logo.png" },
  { id: 5, name: "Planiversity", image: "/images/clients-logo/planiversity.png" },
  { id: 6, name: "JAM", image: "/images/clients-logo/JAM.png" },
  { id: 7, name: "IIHF", image: "/images/clients-logo/IIHF_logo.png" },
  { id: 8, name: "Duma", image: "/images/clients-logo/Moscow_City_Duma_Logo.png" },
  { id: 9, name: "Gazprom", image: "/images/clients-logo/Gazprom_logo.png" },
  { id: 10, name: "Planiversity", image: "/images/clients-logo/planiversity.png" },
  { id: 11, name: "JAM", image: "/images/clients-logo/JAM.png" },
  { id: 12, name: "IIHF", image: "/images/clients-logo/IIHF_logo.png" },
  { id: 13, name: "Duma", image: "/images/clients-logo/Moscow_City_Duma_Logo.png" },
  { id: 14, name: "Gazprom", image: "/images/clients-logo/Gazprom_logo.png" },
  { id: 15, name: "Planiversity", image: "/images/clients-logo/planiversity.png" },
  { id: 16, name: "JAM", image: "/images/clients-logo/JAM.png" },
  { id: 17, name: "IIHF", image: "/images/clients-logo/IIHF_logo.png" },
  { id: 18, name: "Duma", image: "/images/clients-logo/Moscow_City_Duma_Logo.png" },
  { id: 19, name: "Gazprom", image: "/images/clients-logo/Gazprom_logo.png" },
  { id: 20, name: "Planiversity", image: "/images/clients-logo/planiversity.png" },
  { id: 21, name: "JAM", image: "/images/clients-logo/JAM.png" },
  { id: 22, name: "IIHF", image: "/images/clients-logo/IIHF_logo.png" },
  { id: 23, name: "Duma", image: "/images/clients-logo/Moscow_City_Duma_Logo.png" },
  { id: 24, name: "Gazprom", image: "/images/clients-logo/Gazprom_logo.png" },
  { id: 25, name: "Planiversity", image: "/images/clients-logo/planiversity.png" },
  { id: 26, name: "JAM", image: "/images/clients-logo/JAM.png" },
  { id: 27, name: "IIHF", image: "/images/clients-logo/IIHF_logo.png" },
  { id: 28, name: "Duma", image: "/images/clients-logo/Moscow_City_Duma_Logo.png" },
  { id: 29, name: "Gazprom", image: "/images/clients-logo/Gazprom_logo.png" },
  { id: 30, name: "Planiversity", image: "/images/clients-logo/planiversity.png" },
  { id: 31, name: "JAM", image: "/images/clients-logo/JAM.png" },
  { id: 32, name: "IIHF", image: "/images/clients-logo/IIHF_logo.png" },
  { id: 33, name: "Duma", image: "/images/clients-logo/Moscow_City_Duma_Logo.png" },
];

export default logoItems;
